/**
 * The Rust core, as the application uses it.
 *
 * Four surfaces come out of `dither-wasm` and nothing else touches the
 * generated package: the diffusion kernels, the two threshold-tile generators,
 * the shipped hardware palettes, and the SVG tracer.
 *
 * The tracer is here rather than in `export/` for the same reason as the rest
 * of it: this is the one file allowed to hold a `wasm-bindgen` handle, and the
 * tracer's result is one. `export/trace.ts` states what it needs as an
 * interface and `ui/export/session.ts` satisfies it from here.
 *
 * **Handles are freed here and nowhere else.** Everything returned across the
 * boundary that is not a typed array is a `wasm-bindgen` handle holding linear
 * memory until `free()` is called, and every getter on one copies out
 * (docs/API.md, section 1). So each is read once, into plain JS, and released
 * immediately — a rule that is easy to keep in one file and impossible to keep
 * in twenty.
 *
 * The import is dynamic because `src/wasm/pkg` is generated by the `wasm`
 * compose service and is absent in a clean checkout; a static import would turn
 * a missing build into a blank page instead of a message.
 */

import type { Palette } from "../../types/document";
import type { TracedDocument, VectorTraceSettings } from "../../export";
import { logger } from "../../lib/log";
import type { DiffusionPort, DiffusionRequest, DiffusionResult } from "./wasm-backend";
import type { ThresholdRankSource } from "./effects";

const log = logger("wasm");

async function loadModule() {
  const mod = await import("../../wasm/pkg/dither_wasm.js");
  await mod.default();
  return mod;
}

type CoreModule = Awaited<ReturnType<typeof loadModule>>;

export interface CoreKernel {
  readonly id: string;
  readonly name: string;
}

/**
 * What the core's GIF writer reports, with the handle already gone.
 *
 * Field for field what `EncodedGif` carries, read out once and copied, for the
 * reason this whole file exists: every getter on a `wasm-bindgen` handle copies
 * out of linear memory, and a value read after `free()` reads memory the
 * allocator has given to something else.
 */
export interface CoreGifResult {
  readonly bytes: Uint8Array;
  readonly frames: number;
  readonly byteLength: number;
  readonly paletteEntries: number;
  readonly tableEntries: number;
  readonly minCodeSize: number;
  readonly croppedFrames: number;
  readonly pixelsWritten: number;
  readonly transparent: boolean;
}

/**
 * One GIF being built (F-EX-04).
 *
 * Stateful across calls, because the caller renders frames one at a time and
 * cannot hold them all. The handle it wraps lives for the whole animation, which
 * is the one exception to "read it once and free it immediately" in this file —
 * so the two ways it can end are both here and both free it: {@link finish}
 * writes the file, {@link abandon} throws the frames away. A caller that does
 * neither leaks WASM linear memory for the lifetime of the worker, so every path
 * through `worker/render.worker.ts` calls one of them.
 */
export interface CoreGifAnimation {
  /** One frame's index map, one byte per pixel, in playback order. */
  push(indices: Uint8Array): void;
  /** Frames pushed so far, and the bytes of index map held for them. */
  state(): { readonly frames: number; readonly bufferedBytes: number };
  /** Write the file and release the handle. The animation is over either way. */
  finish(
    paletteRgb: Uint8Array,
    delayCentiseconds: number,
    loopForever: boolean,
    transparentIndex: number,
  ): CoreGifResult;
  /** Release the handle without writing anything. Safe to call twice. */
  abandon(): void;
}

/**
 * Everything the application asks of the core, with the handles already gone.
 *
 * `ThresholdRankSource` is part of it rather than beside it because the ordered
 * dithers cannot be built without a tile and the tile has exactly one source.
 */
export interface DitherCore extends ThresholdRankSource, DiffusionPort {
  readonly version: string;
  readonly kernels: readonly CoreKernel[];
  /** The hardware palette library (F-CO-04), in catalogue order. */
  readonly palettes: readonly Palette[];
  /**
   * Trace an index map to SVG (F-EX-08, F-EX-09, F-EX-10).
   *
   * Synchronous, and deliberately: it is one call over a buffer that is already
   * in memory, and making it a promise here would suggest a cancellation point
   * that does not exist inside it. It occupies its thread for as long as the
   * trace takes — but that thread is the render worker, not the one drawing the
   * interface. `worker/render.worker.ts` is the only caller, and
   * `ui/export/session.ts` is what turns the worker's answer back into
   * `export/trace.ts`'s `VectorTracer`.
   */
  traceSvg(
    indices: Uint16Array,
    width: number,
    height: number,
    paletteRgb: Uint8Array,
    settings: VectorTraceSettings,
  ): TracedDocument;
  /**
   * Start an animated GIF (F-EX-04).
   *
   * Here for the same reason `traceSvg` is: the result is a `wasm-bindgen`
   * handle, and this is the one file allowed to hold one. `worker/
   * render.worker.ts` is the only caller, and `ui/export/animated.ts` is what
   * turns the worker's answer back into `export/animated/gif.ts`'s `GifCore`.
   *
   * Throws on an extent GIF cannot describe — the format's dimensions are 16-bit.
   */
  gifAnimation(width: number, height: number): CoreGifAnimation;
}

/** Load and initialise the core. Called once, at boot. */
export async function loadDitherCore(): Promise<DitherCore> {
  const started = performance.now();
  const mod = await loadModule();
  const version = mod.version();

  const kernels = readKernels(mod);
  const palettes = readPalettes(mod);

  log.info("core ready", {
    version,
    kernels: kernels.length,
    palettes: palettes.length,
    ms: Math.round((performance.now() - started) * 100) / 100,
  });

  return {
    version,
    kernels,
    palettes,
    bayerRanks: (size) => mod.bayerRanks(size),
    blueNoiseRanks: (size, seed) => mod.blueNoiseRanks(size, seed),
    dither: (request) => runDither(mod, request),
    traceSvg: (indices, width, height, paletteRgb, settings) =>
      runTrace(mod, indices, width, height, paletteRgb, settings),
    gifAnimation: (width, height) => startGif(mod, width, height),
  };
}

function readKernels(mod: CoreModule): readonly CoreKernel[] {
  const handles = mod.kernels();
  const kernels = handles.map((handle) => ({ id: handle.id, name: handle.name }));
  for (const handle of handles) handle.free();
  return kernels;
}

/**
 * The built-in palettes as documents carry them.
 *
 * Converted here rather than at each call site: `Palette.colors` is a plain
 * number array because that is what JSON round-trips, and the boundary hands
 * over a `Uint8Array` view into WASM memory that stops being valid the moment
 * the handle is freed.
 */
function readPalettes(mod: CoreModule): readonly Palette[] {
  const handles = mod.builtinPalettes();
  const palettes = handles.map((handle) => ({
    id: handle.id,
    name: handle.name,
    colors: Array.from(handle.srgb),
    metric: "oklab" as const,
  }));
  for (const handle of handles) handle.free();
  return palettes;
}

/**
 * One diffusion call.
 *
 * The options object and the output are both handles, and both are freed in a
 * `finally` — a kernel id the core does not have throws from the constructor,
 * and an out-of-range control throws from `ditherImage`, so there are two live
 * failure paths through here and neither may leak.
 */
function runDither(mod: CoreModule, request: DiffusionRequest): DiffusionResult {
  const options = new mod.DitherOptions(request.kernelId);
  try {
    options.strength = request.strength;
    options.serpentine = request.serpentine;
    options.jitter = request.jitter;
    options.seed = request.seed;
    options.overshootLimit = request.overshootLimit;
    options.channels =
      request.channels === "luma"
        ? mod.DiffusionChannels.Luma
        : mod.DiffusionChannels.PerChannel;
    options.metric =
      request.metric === "srgb" ? mod.ColorMetric.Srgb : mod.ColorMetric.Oklab;

    const output = mod.ditherImage(
      request.rgba,
      request.width,
      request.height,
      request.palette,
      options,
    );
    try {
      // Each getter copies out of linear memory; reading them once here is what
      // makes the result safe to hold after the handle is gone.
      return { pixels: output.pixels, indices: output.indices };
    } finally {
      output.free();
    }
  } finally {
    options.free();
  }
}

/**
 * One animated GIF (F-EX-04).
 *
 * The handle outlives the call that made it, which nothing else in this file
 * does — a GIF is built frame by frame and the frames arrive over many messages.
 * That makes the free a discipline rather than a `finally`, so it is enforced
 * here instead of being left to the caller: `#released` makes both endings
 * idempotent, and every subsequent call throws by name rather than reaching into
 * freed memory and producing a picture out of whatever is there now.
 */
function startGif(mod: CoreModule, width: number, height: number): CoreGifAnimation {
  const animation = new mod.GifAnimation(width, height);
  let released = false;

  const live = (what: string): void => {
    if (released) {
      throw new Error(`this GIF animation has already been ${what === "push" ? "finished or abandoned" : "released"}, so it cannot ${what}`);
    }
  };

  return {
    push(indices: Uint8Array): void {
      live("push");
      animation.pushFrame(indices);
    },
    state() {
      live("report");
      return { frames: animation.frameCount, bufferedBytes: animation.bufferedBytes };
    },
    finish(paletteRgb, delayCentiseconds, loopForever, transparentIndex): CoreGifResult {
      live("finish");
      // Freed on the way out whether the encode succeeded or threw: an oversized
      // palette throws from in there, and the animation's own buffer is the
      // largest thing this module ever holds.
      try {
        const encoded = animation.finish(
          paletteRgb,
          delayCentiseconds,
          loopForever,
          transparentIndex,
        );
        try {
          return {
            bytes: encoded.bytes,
            frames: encoded.frames,
            byteLength: encoded.byteLength,
            paletteEntries: encoded.paletteEntries,
            tableEntries: encoded.tableEntries,
            minCodeSize: encoded.minCodeSize,
            croppedFrames: encoded.croppedFrames,
            pixelsWritten: encoded.pixelsWritten,
            transparent: encoded.transparent,
          };
        } finally {
          encoded.free();
        }
      } finally {
        released = true;
        animation.free();
      }
    },
    abandon(): void {
      if (released) return;
      released = true;
      animation.free();
    },
  };
}

/**
 * One trace (F-EX-08).
 *
 * Two handles, both freed in a `finally`, for the reason {@link runDither}
 * gives: every getter copies out of linear memory, and a value read after
 * `free()` is a read of memory the allocator has handed to something else.
 * `traceSvg` throws on a palette index the palette does not have, so the
 * failure path through here is live and neither handle may leak on it.
 */
function runTrace(
  mod: CoreModule,
  indices: Uint16Array,
  width: number,
  height: number,
  paletteRgb: Uint8Array,
  settings: VectorTraceSettings,
): TracedDocument {
  const options = new mod.TraceOptions();
  try {
    options.mode =
      settings.mode === "simplified" ? mod.TraceMode.Simplified : mod.TraceMode.PixelPerfect;
    options.tolerance = settings.tolerance;
    options.minFeatureArea = settings.minFeatureArea;
    options.strokeOnly = settings.strokeOnly;
    options.strokeWidth = settings.strokeWidth;

    const traced = mod.traceSvg(indices, width, height, paletteRgb, options);
    try {
      return {
        svg: traced.svg,
        report: {
          layers: traced.layers,
          contours: traced.contours,
          points: traced.points,
          contoursDropped: traced.contoursDropped,
          regionsDropped: traced.regionsDropped,
          regionPixelsDropped: traced.regionPixelsDropped,
          holesFilled: traced.holesFilled,
          holePixelsFilled: traced.holePixelsFilled,
          uncoveredPixels: traced.uncoveredPixels,
        },
      };
    } finally {
      traced.free();
    }
  } finally {
    options.free();
  }
}
