/**
 * The Rust core, as the renderer uses it.
 *
 * Three surfaces come out of `dither-wasm` and nothing else in the render path
 * touches the generated package: the diffusion kernels, the two threshold-tile
 * generators, and the shipped hardware palettes.
 *
 * **Handles are freed here and nowhere else.** Everything returned across the
 * boundary that is not a typed array is a `wasm-bindgen` handle holding linear
 * memory until `free()` is called, and every getter on one copies out
 * (docs/API.md, section 1). So each is read once, into plain JS, and released
 * immediately — a rule that is easy to keep in one file and impossible to keep
 * in twenty.
 *
 * The import is dynamic because `src/wasm/pkg` is generated by the `wasm`
 * compose service and is absent in a clean checkout; a static import would turn
 * a missing build into a blank page instead of a message.
 */

import type { Palette } from "../../types/document";
import { logger } from "../../lib/log";
import type { DiffusionPort, DiffusionRequest, DiffusionResult } from "./wasm-backend";
import type { ThresholdRankSource } from "./effects";

const log = logger("wasm");

async function loadModule() {
  const mod = await import("../../wasm/pkg/dither_wasm.js");
  await mod.default();
  return mod;
}

type CoreModule = Awaited<ReturnType<typeof loadModule>>;

export interface CoreKernel {
  readonly id: string;
  readonly name: string;
}

/**
 * Everything the application asks of the core, with the handles already gone.
 *
 * `ThresholdRankSource` is part of it rather than beside it because the ordered
 * dithers cannot be built without a tile and the tile has exactly one source.
 */
export interface DitherCore extends ThresholdRankSource, DiffusionPort {
  readonly version: string;
  readonly kernels: readonly CoreKernel[];
  /** The hardware palette library (F-CO-04), in catalogue order. */
  readonly palettes: readonly Palette[];
}

/** Load and initialise the core. Called once, at boot. */
export async function loadDitherCore(): Promise<DitherCore> {
  const started = performance.now();
  const mod = await loadModule();
  const version = mod.version();

  const kernels = readKernels(mod);
  const palettes = readPalettes(mod);

  log.info("core ready", {
    version,
    kernels: kernels.length,
    palettes: palettes.length,
    ms: Math.round((performance.now() - started) * 100) / 100,
  });

  return {
    version,
    kernels,
    palettes,
    bayerRanks: (size) => mod.bayerRanks(size),
    blueNoiseRanks: (size, seed) => mod.blueNoiseRanks(size, seed),
    dither: (request) => runDither(mod, request),
  };
}

function readKernels(mod: CoreModule): readonly CoreKernel[] {
  const handles = mod.kernels();
  const kernels = handles.map((handle) => ({ id: handle.id, name: handle.name }));
  for (const handle of handles) handle.free();
  return kernels;
}

/**
 * The built-in palettes as documents carry them.
 *
 * Converted here rather than at each call site: `Palette.colors` is a plain
 * number array because that is what JSON round-trips, and the boundary hands
 * over a `Uint8Array` view into WASM memory that stops being valid the moment
 * the handle is freed.
 */
function readPalettes(mod: CoreModule): readonly Palette[] {
  const handles = mod.builtinPalettes();
  const palettes = handles.map((handle) => ({
    id: handle.id,
    name: handle.name,
    colors: Array.from(handle.srgb),
    metric: "oklab" as const,
  }));
  for (const handle of handles) handle.free();
  return palettes;
}

/**
 * One diffusion call.
 *
 * The options object and the output are both handles, and both are freed in a
 * `finally` — a kernel id the core does not have throws from the constructor,
 * and an out-of-range control throws from `ditherImage`, so there are two live
 * failure paths through here and neither may leak.
 */
function runDither(mod: CoreModule, request: DiffusionRequest): DiffusionResult {
  const options = new mod.DitherOptions(request.kernelId);
  try {
    options.strength = request.strength;
    options.serpentine = request.serpentine;
    options.jitter = request.jitter;
    options.seed = request.seed;
    options.overshootLimit = request.overshootLimit;
    options.channels =
      request.channels === "luma"
        ? mod.DiffusionChannels.Luma
        : mod.DiffusionChannels.PerChannel;
    options.metric =
      request.metric === "srgb" ? mod.ColorMetric.Srgb : mod.ColorMetric.Oklab;

    const output = mod.ditherImage(
      request.rgba,
      request.width,
      request.height,
      request.palette,
      options,
    );
    try {
      // Each getter copies out of linear memory; reading them once here is what
      // makes the result safe to hold after the handle is gone.
      return { pixels: output.pixels, indices: output.indices };
    } finally {
      output.free();
    }
  } finally {
    options.free();
  }
}
