/**
 * F-PT-07 — Classical clustered-dot ordered screen.
 *
 * ## What the screen is, and where it comes from
 *
 * A clustered-dot screen is the printing screen: at every tone the pixels that
 * are on form one compact dot per screen cell, and the dot grows outward from
 * the cell centre as the tone darkens. It is the exact opposite of Bayer, whose
 * recursion maximally *disperses* the same pixels, and it cannot be reached by
 * blurring or reordering a Bayer tile.
 *
 * The family is classically published as a set of integer threshold matrices —
 * Ulichney, *Digital Halftoning* (1987) §5.1, and the same tables reproduced in
 * Netpbm as `cluster3`/`cluster4`/`cluster8`. **The tables are not transcribed
 * here; they are constructed from the definition they are tabulations of**,
 * which is what lets the effect offer the whole family rather than the three
 * sizes that happen to be in print, and what removes the risk of a mistyped
 * cell in a hand-copied matrix:
 *
 * 1. Dot centres sit on a lattice. `orthogonal` uses the axis-aligned lattice
 *    with spacing `cell`, so the tile is `cell × cell` and holds one dot.
 *    `diagonal` uses the centred-square lattice generated by `(n, n)` and
 *    `(n, −n)`, the classical 45° screen: its cells hold `2n²` pixels, its
 *    smallest axis-aligned period is `2n × 2n`, and that tile holds two dots.
 *    (That is exactly the structure of the published tables, whose values each
 *    appear twice.)
 * 2. Every pixel of the tile is ordered by distance from its nearest dot
 *    centre, ties broken by the angle about that centre — the spiral growth the
 *    family is named for — and finally by row then column, so the order is a
 *    strict total order and the result is reproducible.
 * 3. Rank `k` of `A` becomes the threshold `(k + 0.5) / A`.
 *
 * Because the ranks are a permutation, the thresholds are uniformly distributed
 * over the tile and the screen reproduces tone exactly. The published tables
 * give the two dots of a 45° tile equal values; ranking the whole tile splits
 * those ties into adjacent levels instead, which is the same screen with twice
 * the tonal resolution and at most a one-pixel difference in dot size at any
 * given tone.
 *
 * Where the published matrices start their spiral is a convention — rotating
 * the growth order rotates the dot and changes nothing tonal — so this
 * construction reproduces their level sets, not necessarily their exact
 * numbering.
 *
 * ## Why the whole family ships as one table
 *
 * A `table` binding is uploaded once when the pipeline is compiled and cannot
 * change per parameter, but cell size and angle *are* parameters. So every
 * screen is concatenated into one buffer behind a header and the uniform picks
 * one. It costs about 30 KB and it keeps the effect a single registry entry
 * instead of thirty.
 */

import { defineEffect, type ParamDescriptor } from "../types/registry";
import type { ParameterValue } from "../types/document";
import type {
  ComputePass,
  GpuEffect,
  PassBinding,
  UniformLayout,
} from "../types/gpu";
import { logger } from "../lib/log";

import wgsl from "../shaders/clustered-dot.wgsl?raw";

const log = logger("gpu");

export const CLUSTERED_DOT_ID = "clustered-dot";

/** Canonical binding numbers, restated from `shaders/CONVENTIONS.md`. */
const BINDING = {
  inputColor: 0,
  outputColor: 1,
  outputIndex: 3,
  palette: 4,
  uniforms: 5,
  screens: 6,
} as const;

/** Parameter keys, in one place so the shader struct and the packer agree. */
export const CLUSTERED_DOT_PARAM = {
  cellSize: "cellSize",
  angle: "angle",
  offsetX: "offsetX",
  offsetY: "offsetY",
  contrast: "contrast",
  spread: "spread",
  thresholdOffset: "thresholdOffset",
} as const;

/**
 * Screen angles, in the order their ordinal reaches the shader.
 *
 * The uniform packer turns an enum value into its position in the descriptor's
 * `values` list, and the shader uses that position to index the table's mode
 * blocks. Both are derived from this one array so the two orders cannot drift —
 * inserting a mode in the middle would otherwise silently renumber every
 * document already saved.
 */
const ANGLE_MODES = [
  { value: "diagonal", label: "45° (classical)" },
  { value: "orthogonal", label: "0° (orthogonal)" },
] as const;

/** Smallest and largest cell the table carries. */
const MIN_CELL = 2;
const MAX_CELL = 16;
const SIZE_COUNT = MAX_CELL - MIN_CELL + 1;

/** Words of table header before the per-screen directory. Restated in the WGSL. */
const HEADER_WORDS = 4;

/**
 * The uniform block, byte for byte as `struct Params` declares it in
 * `../shaders/clustered-dot.wgsl`.
 *
 * Every slot is a 4-byte scalar, so no field needs padding in front of it and
 * the only padding is the tail that rounds 36 up to 48.
 */
export const CLUSTERED_DOT_UNIFORMS: UniformLayout = {
  sizeBytes: 48,
  fields: [
    { source: { kind: "builtin", name: "width" }, type: "u32", offset: 0 },
    { source: { kind: "builtin", name: "height" }, type: "u32", offset: 4 },
    { source: { kind: "param", key: CLUSTERED_DOT_PARAM.cellSize }, type: "u32", offset: 8 },
    { source: { kind: "param", key: CLUSTERED_DOT_PARAM.angle }, type: "u32", offset: 12 },
    { source: { kind: "param", key: CLUSTERED_DOT_PARAM.offsetX }, type: "f32", offset: 16 },
    { source: { kind: "param", key: CLUSTERED_DOT_PARAM.offsetY }, type: "f32", offset: 20 },
    { source: { kind: "param", key: CLUSTERED_DOT_PARAM.contrast }, type: "f32", offset: 24 },
    { source: { kind: "param", key: CLUSTERED_DOT_PARAM.spread }, type: "f32", offset: 28 },
    {
      source: { kind: "param", key: CLUSTERED_DOT_PARAM.thresholdOffset },
      type: "f32",
      offset: 32,
    },
  ],
};

const PARAMS: readonly ParamDescriptor[] = [
  {
    key: CLUSTERED_DOT_PARAM.cellSize,
    label: "Cell size",
    type: "int",
    hint: "Screen ruling, in pixels between dot centres. Larger cells give coarser dots and more tonal levels.",
    // Not animatable: the value reaches the shader as a u32 and the uniform
    // packer refuses a non-integer for one, so a modulator bound here would
    // fail the pack rather than round. It also selects a different screen
    // outright, so interpolating it would pop rather than move.
    animatable: false,
    legal: [MIN_CELL, MAX_CELL],
    default: 4,
    // Below 3 the dot is a couple of pixels and the screen stops reading as a
    // halftone; above 8 the cell is visible as a grid at 1x on most images.
    surprise: { range: [3, 8], distribution: { kind: "uniform" }, weight: 1.2 },
  },
  {
    key: CLUSTERED_DOT_PARAM.angle,
    label: "Screen angle",
    type: "enum",
    hint: "45° is the classical screen: its dot lattice is the one printing uses because the grid is least visible there.",
    animatable: false,
    values: ANGLE_MODES.map((mode) => ({ value: mode.value, label: mode.label })),
    default: "diagonal",
    surprise: {
      // 45° is what "clustered dot" means to the eye; 0° reads as a visible
      // square grid and is the deliberate deviation.
      values: [
        { value: "diagonal", weight: 3 },
        { value: "orthogonal", weight: 1 },
      ],
      weight: 0.7,
    },
  },
  {
    key: CLUSTERED_DOT_PARAM.offsetX,
    label: "Offset X",
    type: "float",
    // An ordered screen is locked to the pixel grid — that is what makes it an
    // ordered screen rather than a resampled halftone — so the offset takes
    // effect in whole pixels and a fractional value floors.
    hint: "Shifts the screen horizontally, in whole pixels.",
    animatable: true,
    legal: [-1024, 1024],
    default: 0,
    surprise: { range: [-8, 8], distribution: { kind: "uniform" }, weight: 0.5 },
  },
  {
    key: CLUSTERED_DOT_PARAM.offsetY,
    label: "Offset Y",
    type: "float",
    hint: "Shifts the screen vertically, in whole pixels.",
    animatable: true,
    legal: [-1024, 1024],
    default: 0,
    surprise: { range: [-8, 8], distribution: { kind: "uniform" }, weight: 0.5 },
  },
  {
    key: CLUSTERED_DOT_PARAM.contrast,
    label: "Screen contrast",
    type: "float",
    hint: "Steepens the screen around its midpoint. Above 1 hardens the dot into an on/off blob.",
    animatable: true,
    legal: [0.05, 4],
    default: 1,
    surprise: { range: [0.6, 1.8], distribution: { kind: "log" }, weight: 0.8 },
  },
  {
    key: CLUSTERED_DOT_PARAM.spread,
    label: "Spread",
    type: "float",
    hint: "Dither strength. 0 is plain quantization, 1 reproduces tone exactly.",
    animatable: true,
    legal: [0, 2],
    default: 1,
    surprise: { range: [0.4, 1.2], distribution: { kind: "uniform" }, weight: 1 },
  },
  {
    key: CLUSTERED_DOT_PARAM.thresholdOffset,
    label: "Threshold offset",
    type: "float",
    hint: "Slides the cut between the two candidate colours. ±0.5 forces one.",
    animatable: true,
    legal: [-0.5, 0.5],
    default: 0,
    surprise: { range: [-0.15, 0.15], distribution: { kind: "uniform" }, weight: 0.6 },
  },
];

/** Parameter descriptors keyed for `packUniforms`. */
export const CLUSTERED_DOT_PARAM_TYPES: ReadonlyMap<string, ParamDescriptor> = new Map(
  PARAMS.map((param) => [param.key, param]),
);

/** Defaults, for a node created without an explicit parameter set. */
export function clusteredDotDefaults(): Record<string, ParameterValue> {
  const defaults: Record<string, ParameterValue> = {};
  for (const param of PARAMS) {
    switch (param.type) {
      case "float":
      case "int":
      case "enum":
        defaults[param.key] = param.default;
        break;
      default:
        break;
    }
  }
  return defaults;
}

// --- screen construction ------------------------------------------------

export class ClusteredDotScreenError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ClusteredDotScreenError";
  }
}

/** One tile pixel, with everything the growth order sorts on. */
interface Cell {
  readonly x: number;
  readonly y: number;
  /** Squared distance to the nearest dot centre. Exact: every term is a multiple of 1/4. */
  readonly d2: number;
  /** Offset from that centre, used for the angular tie-break. */
  readonly dx: number;
  readonly dy: number;
  /** Which dot claimed it, reduced into the tile so translates count as one. */
  readonly owner: number;
}

/**
 * Identify a dot centre by its position modulo the tile.
 *
 * Centres fall on half-integers when the cell size is odd, so the coordinates
 * are doubled to stay integral before the reduction. Reducing at all is the
 * point: the same dot appears at many lattice indices, and the count check
 * below is asking how many *distinct* dots the tile holds.
 */
function dotKey(cx: number, cy: number, tile: number): number {
  const period = tile * 2;
  const kx = (((cx * 2) % period) + period) % period;
  const ky = (((cy * 2) % period) + period) % period;
  return ky * period + kx;
}

/**
 * Half-plane a direction falls in, splitting at the positive x axis.
 *
 * Half 0 is the angular range `[0, pi)`, half 1 is `[pi, 2pi)`. Together with
 * the cross-product test below this orders directions by angle using only exact
 * arithmetic on half-integers — no `atan2`, whose last bit is not required to
 * agree between platforms and would be the one thing in this construction that
 * could rank two pixels differently on two machines.
 */
function halfPlane(dx: number, dy: number): number {
  return dy > 0 || (dy === 0 && dx > 0) ? 0 : 1;
}

/**
 * The dot-growth order: distance first, then angle, then row and column.
 *
 * The final row/column tie-break is not decoration. On a 45° screen the two
 * dots of a tile are exact translates of each other, so their corresponding
 * pixels agree on distance *and* angle; without a last resort the sort would
 * not be a strict weak ordering and the ranks would depend on the sort's
 * implementation.
 */
function compareCells(a: Cell, b: Cell): number {
  if (a.d2 !== b.d2) return a.d2 - b.d2;
  const ha = halfPlane(a.dx, a.dy);
  const hb = halfPlane(b.dx, b.dy);
  if (ha !== hb) return ha - hb;
  const cross = a.dx * b.dy - a.dy * b.dx;
  if (cross !== 0) return cross > 0 ? -1 : 1;
  if (a.y !== b.y) return a.y - b.y;
  return a.x - b.x;
}

/**
 * Build one screen.
 *
 * @param cell dot spacing in pixels.
 * @param diagonal true for the classical 45° centred-square lattice, false for
 * the axis-aligned one.
 */
function buildScreen(cell: number, diagonal: boolean): {
  readonly tile: number;
  readonly ranks: Uint32Array;
} {
  const tile = diagonal ? cell * 2 : cell;
  const area = tile * tile;
  const expectedPerDot = diagonal ? 2 * cell * cell : cell * cell;

  const cells: Cell[] = [];
  for (let y = 0; y < tile; y += 1) {
    for (let x = 0; x < tile; x += 1) {
      const px = x + 0.5;
      const py = y + 0.5;

      let bestD2 = Number.POSITIVE_INFINITY;
      let bestDx = 0;
      let bestDy = 0;
      let bestCx = 0;
      let bestCy = 0;

      // A window of two lattice steps either side of the pixel always contains
      // the nearest centre for both lattices; the loop is cheap enough that
      // widening it costs nothing and narrowing it would need a proof.
      const u0 = Math.floor((px - cell / 2) / cell) - 2;
      const v0 = Math.floor((py - cell / 2) / cell) - 2;
      for (let v = v0; v <= v0 + 4; v += 1) {
        for (let u = u0; u <= u0 + 4; u += 1) {
          // The 45° lattice is the subset of the square lattice whose two
          // indices share a parity — the centred-square lattice generated by
          // (n, n) and (n, -n).
          if (diagonal && (((u + v) % 2) + 2) % 2 !== 0) continue;
          const cx = u * cell + cell / 2;
          const cy = v * cell + cell / 2;
          const dx = px - cx;
          const dy = py - cy;
          const d2 = dx * dx + dy * dy;
          // Ties are broken on the centre's own position, which is invariant
          // under the lattice translations that map one dot of the tile onto
          // the other — so both dots come out the same shape and the same size.
          const better =
            d2 < bestD2 ||
            (d2 === bestD2 && (cy < bestCy || (cy === bestCy && cx < bestCx)));
          if (better) {
            bestD2 = d2;
            bestDx = dx;
            bestDy = dy;
            bestCx = cx;
            bestCy = cy;
          }
        }
      }

      cells.push({
        x,
        y,
        d2: bestD2,
        dx: bestDx,
        dy: bestDy,
        owner: dotKey(bestCx, bestCy, tile),
      });
    }
  }

  const counts = new Map<number, number>();
  for (const c of cells) counts.set(c.owner, (counts.get(c.owner) ?? 0) + 1);
  for (const [owner, count] of counts) {
    if (count !== expectedPerDot) {
      // A lattice or tie-break mistake shows up here as unequal dots, which
      // would otherwise be a screen that halftones, looks broadly right, and
      // reproduces tone wrong in one of its two dots.
      throw new ClusteredDotScreenError(
        `clustered-dot ${diagonal ? "45" : "0"}deg cell ${cell}: dot ${owner} owns ${count} pixels, expected ${expectedPerDot}`,
      );
    }
  }
  if (counts.size !== area / expectedPerDot) {
    throw new ClusteredDotScreenError(
      `clustered-dot ${diagonal ? "45" : "0"}deg cell ${cell}: tile holds ${counts.size} dots, expected ${area / expectedPerDot}`,
    );
  }

  const order = [...cells].sort(compareCells);
  const ranks = new Uint32Array(area);
  const seen = new Uint8Array(area);
  order.forEach((c, rank) => {
    const at = c.y * tile + c.x;
    if (seen[at] === 1) {
      throw new ClusteredDotScreenError(
        `clustered-dot cell ${cell}: pixel ${c.x},${c.y} was ranked twice`,
      );
    }
    seen[at] = 1;
    ranks[at] = rank;
  });

  return { tile, ranks };
}

/**
 * The whole family, packed as the shader reads it.
 *
 * Layout, all u32: a four-word header (`screenCount`, `minCell`, `sizeCount`,
 * `modeCount`), then two words per screen (`tile`, word offset of its ranks),
 * then the ranks. See `../shaders/clustered-dot.wgsl` for the reading side.
 */
export function buildClusteredDotScreens(): Uint32Array {
  const built: { tile: number; ranks: Uint32Array }[] = [];
  for (const mode of ANGLE_MODES) {
    for (let cell = MIN_CELL; cell <= MAX_CELL; cell += 1) {
      built.push(buildScreen(cell, mode.value === "diagonal"));
    }
  }

  const directory = built.length * 2;
  const dataWords = built.reduce((total, screen) => total + screen.ranks.length, 0);
  const words = new Uint32Array(HEADER_WORDS + directory + dataWords);

  words[0] = built.length;
  words[1] = MIN_CELL;
  words[2] = SIZE_COUNT;
  words[3] = ANGLE_MODES.length;

  let cursor = HEADER_WORDS + directory;
  built.forEach((screen, index) => {
    words[HEADER_WORDS + index * 2] = screen.tile;
    words[HEADER_WORDS + index * 2 + 1] = cursor;
    words.set(screen.ranks, cursor);
    cursor += screen.ranks.length;
  });

  log.debug("clustered-dot screens built", {
    screens: built.length,
    bytes: words.byteLength,
  });
  return words;
}

/** Built once and kept: the table is constant and the sorts are not free. */
let screenTable: Uint32Array | null = null;

function clusteredDotScreenBytes(): Uint8Array {
  if (screenTable === null) screenTable = buildClusteredDotScreens();
  // A view, not a copy. Uint32Array already uses host byte order and WebGPU
  // buffer contents are host byte order, so the shader's array<u32> reads
  // exactly these words.
  return new Uint8Array(screenTable.buffer, screenTable.byteOffset, screenTable.byteLength);
}

/**
 * The compute pass.
 *
 * One dispatch, pointwise: the threshold comes from the pixel's own coordinate
 * and nothing is read from a neighbour.
 */
export function clusteredDotGpuEffect(): GpuEffect {
  const bindings: readonly PassBinding[] = [
    { role: "input-color", binding: BINDING.inputColor },
    { role: "output-color", binding: BINDING.outputColor },
    { role: "output-index", binding: BINDING.outputIndex },
    { role: "palette", binding: BINDING.palette },
    { role: "uniforms", binding: BINDING.uniforms },
    { role: "table", binding: BINDING.screens, data: clusteredDotScreenBytes() },
  ];

  const pass: ComputePass = {
    id: `${CLUSTERED_DOT_ID}/screen`,
    label: "Clustered-dot screen",
    wgsl,
    entryPoint: "main",
    // 64 invocations, well under the 256 guaranteed everywhere.
    workgroupSize: [8, 8, 1],
    dispatch: { kind: "per-pixel" },
    access: "pointwise",
    bindings,
    uniforms: CLUSTERED_DOT_UNIFORMS,
  };

  return { effect: CLUSTERED_DOT_ID, passes: [pass] };
}

export default defineEffect({
  id: CLUSTERED_DOT_ID,
  name: "Clustered-dot screen",
  requirement: "F-PT-07",
  slot: "dither",
  family: "pattern",
  execution: "gpu",
  params: PARAMS,
  // The signature look of the pattern family and the one that flatters the most
  // images, so it sits with the Bayer tiles rather than below them.
  surpriseWeight: 1,
  // Quantizing is the point: the index map it emits is what makes outline,
  // dilate/erode, hue-targeted recolour and the tracer lossless downstream.
  producesIndexMap: true,
  requiresIndexMap: false,
});
