/**
 * Scaffold entry point.
 *
 * Does three things, in order: run the startup capability check, load the WASM
 * core, and dither a generated test image so a fresh `docker compose up` proves
 * the whole chain end to end — headers, threads, WASM boundary, colour path.
 */

import { checkCapabilities, type Capability } from "./lib/capabilities";
import { correlationId, logger } from "./lib/log";

const log = logger("app", correlationId());

const CAPABILITY_TABLE = document.querySelector<HTMLTableSectionElement>(
  "#capabilities tbody",
);
const CORE_STATUS = document.querySelector<HTMLDivElement>("#core-status");
const SMOKE = document.querySelector<HTMLDivElement>("#smoke");

function renderCapabilities(caps: readonly Capability[]): void {
  if (!CAPABILITY_TABLE) return;
  CAPABILITY_TABLE.innerHTML = "";
  for (const c of caps) {
    const row = document.createElement("tr");
    const cls = c.state === "ok" ? "ok" : c.fatal ? "fail" : "warn";
    const mark = c.state === "ok" ? "OK" : c.fatal ? "FAIL" : "WARN";
    row.innerHTML =
      `<td class="state ${cls}">${mark}</td>` +
      `<td>${c.label}</td>` +
      `<td class="detail">${c.detail}</td>`;
    CAPABILITY_TABLE.append(row);
  }
}

/** A gradient with a couple of bands, enough to show banding and diffusion. */
function testImage(width: number, height: number): ImageData {
  const data = new Uint8ClampedArray(width * height * 4);
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const i = (y * width + x) * 4;
      const ramp = x / (width - 1);
      const band = 0.5 + 0.5 * Math.sin((y / height) * Math.PI * 3);
      const v = Math.round(255 * ramp * band);
      data[i] = v;
      data[i + 1] = v;
      data[i + 2] = v;
      data[i + 3] = 255;
    }
  }
  return new ImageData(data, width, height);
}

function showCanvas(caption: string, image: ImageData, scale: number): void {
  if (!SMOKE) return;
  const canvas = document.createElement("canvas");
  canvas.width = image.width * scale;
  canvas.height = image.height * scale;

  const buffer = document.createElement("canvas");
  buffer.width = image.width;
  buffer.height = image.height;
  buffer.getContext("2d")?.putImageData(image, 0, 0);

  const ctx = canvas.getContext("2d");
  if (ctx) {
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(buffer, 0, 0, canvas.width, canvas.height);
  }

  const figure = document.createElement("figure");
  figure.append(canvas);
  const cap = document.createElement("figcaption");
  cap.textContent = caption;
  figure.append(cap);
  SMOKE.append(figure);
}

async function loadCore() {
  // Generated by the `wasm` compose service into src/wasm/pkg. The import is
  // dynamic so a missing build produces a clear message instead of a blank page.
  const mod = await import("./wasm/pkg/dither_wasm.js");
  await mod.default();
  return mod;
}

async function main(): Promise<void> {
  const report = await log.time("capability check", checkCapabilities);
  renderCapabilities(report.capabilities);

  if (!report.usable) {
    const names = report.fatalFailures.map((c) => c.label).join(", ");
    if (CORE_STATUS) {
      CORE_STATUS.innerHTML =
        `<span class="fail">blocked</span> — missing: ${names}. ` +
        `See docs/ARCHITECTURE.md, "Platform support policy".`;
    }
    log.error("startup blocked", { missing: names });
    return;
  }

  let core: Awaited<ReturnType<typeof loadCore>>;
  try {
    core = await log.time("load wasm core", loadCore);
  } catch (error) {
    if (CORE_STATUS) {
      CORE_STATUS.innerHTML =
        `<span class="fail">not built</span> — run <code>docker compose up wasm</code>, ` +
        `or check that src/wasm/pkg exists.`;
    }
    log.error("wasm core failed to load", { error: String(error) });
    return;
  }

  const kernels = core.kernel_ids().split("\n").filter(Boolean);
  if (CORE_STATUS) {
    CORE_STATUS.innerHTML =
      `<span class="ok">loaded</span> — dither-core v${core.version()}, ` +
      `kernels: ${kernels.join(", ")}`;
  }
  log.info("core loaded", { version: core.version(), kernels: kernels.length });

  const source = testImage(160, 96);
  showCanvas("source", source, 3);

  // Game Boy DMG, the same four values the core ships as a built-in.
  const palette = new Uint8Array([
    0x08, 0x18, 0x20, 0x34, 0x68, 0x56, 0x88, 0xc0, 0x70, 0xe0, 0xf8, 0xd0,
  ]);

  for (const kernel of kernels) {
    const out = await log.time(`dither ${kernel}`, () =>
      core.dither_image(
        new Uint8Array(source.data.buffer),
        source.width,
        source.height,
        palette,
        kernel,
        1.0,
        true,
        "oklab",
      ),
    );
    const image = new ImageData(
      new Uint8ClampedArray(out.pixels),
      out.width,
      out.height,
    );
    showCanvas(kernel, image, 3);
  }
}

main().catch((error: unknown) => {
  log.error("fatal", { error: String(error) });
});
